import { useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAdmin } from "../admin/AdminContext";
import ContentComposer from "../components/admin/ContentComposer";
import ContentFeed from "../components/admin/ContentFeed";

export default function AdminDashboardPage() {
  const { applications, content, isConfigured, logout, markNotificationRead, notifications, publish, session } = useAdmin();
  const navigate = useNavigate();
  const [composerOpen, setComposerOpen] = useState(false);
  if (!session) return null;
  const ministryContent = content.filter((item) => item.ministry === session.role);
  const unreadNotifications = notifications.filter((item) => !item.readAt);
  const applicationRows = useMemo(() => [...applications].sort((left, right) => new Date(right.createdAt).getTime() - new Date(left.createdAt).getTime()), [applications]);

  const exit = async () => { await logout(); navigate("/admin/login", { replace: true }); };
  return <main className="min-h-dvh px-6 py-8 md:px-12" style={{ backgroundColor: "var(--color-parchment)" }}>
    <header className="mx-auto flex max-w-6xl flex-col gap-5 border-b pb-7 sm:flex-row sm:items-center sm:justify-between" style={{ borderColor: "rgba(184,137,42,0.25)" }}><div><p className="text-xs uppercase" style={{ color: "var(--color-gold)", fontFamily: "var(--font-display)", letterSpacing: "0.16em" }}>Catholic Ministries · administration</p><h1 className="mt-1 text-4xl" style={{ color: "var(--color-ink)", fontFamily: "var(--font-display)" }}>{session.role} ministry desk</h1><p className="mt-2" style={{ color: "var(--color-stone)" }}>Signed in as {session.name}</p></div><div className="flex flex-wrap gap-3"><Link className="btn-quiet" to="/stories">View stories</Link><Link className="btn-quiet" to="/">Parish home</Link><button className="btn-quiet cursor-pointer" onClick={exit} type="button">Log out</button></div></header>
    {!isConfigured && <div className="mx-auto mt-8 max-w-6xl border p-5" role="status" style={{ backgroundColor: "#fff9f0", borderColor: "rgba(184,137,42,0.35)" }}><p style={{ color: "var(--color-ink-light)" }}>Preview mode is active. Add Supabase environment values and run the supplied SQL script before using this dashboard for live submissions.</p></div>}
    <section className="mx-auto mt-10 grid max-w-6xl gap-6 lg:grid-cols-[1fr_0.9fr]"><div className="border p-7" style={{ backgroundColor: "#fff9f0", borderColor: "rgba(184,137,42,0.25)" }}><p className="text-xs uppercase" style={{ color: "var(--color-gold)", fontFamily: "var(--font-display)", letterSpacing: "0.15em" }}>Content studio</p><h2 className="mt-2 text-3xl" style={{ color: "var(--color-ink)", fontFamily: "var(--font-display)" }}>Tell the next story</h2><p className="mt-4 max-w-xl leading-7" style={{ color: "var(--color-stone)" }}>Your active {session.role} role is attached automatically. Photo posts expire from the public feed after 30 days; articles and announcements remain published.</p><button className="btn-primary mt-7 cursor-pointer" onClick={() => setComposerOpen(true)} type="button">Create post</button></div><aside className="border p-7" style={{ backgroundColor: "var(--color-ink)", borderColor: "rgba(212,168,67,0.35)" }}><p className="text-xs uppercase" style={{ color: "var(--color-gold-light)", fontFamily: "var(--font-display)", letterSpacing: "0.16em" }}>At a glance</p><dl className="mt-6 space-y-4"><Metric label={`Published by ${session.role}`} value={ministryContent.length} /><Metric label="New applications" value={unreadNotifications.length} /><Metric label="Applications received" value={applicationRows.length} /></dl></aside></section>
    <section className="mx-auto mt-14 max-w-6xl"><div className="mb-6 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs uppercase" style={{ color: "var(--color-gold)", fontFamily: "var(--font-display)", letterSpacing: "0.16em" }}>Membership inbox</p><h2 className="mt-1 text-3xl" style={{ color: "var(--color-ink)", fontFamily: "var(--font-display)" }}>Applications</h2></div><span className="text-sm" style={{ color: "var(--color-stone)" }}>Newest first</span></div><ApplicationsTable applications={applicationRows} /></section>
    <section className="mx-auto mt-14 max-w-6xl"><p className="text-xs uppercase" style={{ color: "var(--color-gold)", fontFamily: "var(--font-display)", letterSpacing: "0.16em" }}>Admin notifications</p><h2 className="mt-1 mb-6 text-3xl" style={{ color: "var(--color-ink)", fontFamily: "var(--font-display)" }}>What needs your attention</h2><div className="grid gap-4 md:grid-cols-2">{notifications.length ? notifications.map((notification) => <article className="border p-5" key={notification.id} style={{ backgroundColor: notification.readAt ? "rgba(247,237,216,0.5)" : "#fff9f0", borderColor: "rgba(184,137,42,0.25)" }}><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase" style={{ color: "var(--color-gold)", fontFamily: "var(--font-display)", letterSpacing: "0.12em" }}>{notification.type.replace("_", " ")}</p><h3 className="mt-1 text-xl" style={{ color: "var(--color-ink)", fontFamily: "var(--font-display)" }}>{notification.title}</h3></div>{!notification.readAt && <button className="btn-quiet cursor-pointer" onClick={() => void markNotificationRead(notification.id)} type="button">Mark read</button>}</div><p className="mt-3 leading-7" style={{ color: "var(--color-stone)" }}>{notification.message}</p><p className="mt-3 text-sm" style={{ color: "var(--color-stone)" }}>{new Date(notification.createdAt).toLocaleString()}</p></article>) : <p className="border p-6" style={{ color: "var(--color-stone)", borderColor: "rgba(184,137,42,0.25)" }}>No notifications yet.</p>}</div></section>
    <section className="mx-auto mt-14 max-w-6xl"><p className="text-xs uppercase" style={{ color: "var(--color-gold)", fontFamily: "var(--font-display)", letterSpacing: "0.16em" }}>Your ministry's recent work</p><h2 className="mt-1 mb-6 text-3xl" style={{ color: "var(--color-ink)", fontFamily: "var(--font-display)" }}>Published updates</h2><ContentFeed content={ministryContent} emptyMessage="Your ministry has not published an update yet." /></section>
    {composerOpen && <ContentComposer onClose={() => setComposerOpen(false)} onPublish={publish} />}
  </main>;
}

function Metric({ label, value }: { label: string; value: number }) {
  return <div className="flex items-center justify-between gap-4 border-b pb-4" style={{ borderColor: "rgba(212,168,67,0.25)" }}><dt style={{ color: "rgba(247,237,216,0.72)" }}>{label}</dt><dd className="text-2xl" style={{ color: "var(--color-gold-light)", fontFamily: "var(--font-display)" }}>{value}</dd></div>;
}

function ApplicationsTable({ applications }: { applications: ReturnType<typeof useAdmin>["applications"] }) {
  if (!applications.length) return <div className="border p-8 text-center" style={{ borderColor: "rgba(184,137,42,0.25)", backgroundColor: "#fff9f0" }}><p style={{ color: "var(--color-stone)" }}>No membership applications have arrived for your ministry yet.</p></div>;
  return <div className="overflow-x-auto border" style={{ borderColor: "rgba(184,137,42,0.25)", backgroundColor: "#fff9f0" }}><table className="min-w-[860px] w-full text-left text-sm"><thead style={{ backgroundColor: "var(--color-ink)", color: "var(--color-parchment)" }}><tr>{["Applicant", "Program", "Year / Section", "Contact", "Submitted"].map((heading) => <th className="px-5 py-4 font-normal uppercase" key={heading} style={{ fontFamily: "var(--font-display)", letterSpacing: "0.1em" }}>{heading}</th>)}</tr></thead><tbody>{applications.map((application) => <tr className="border-t" key={application.id} style={{ borderColor: "rgba(184,137,42,0.18)" }}><td className="px-5 py-4"><p style={{ color: "var(--color-ink)" }}>{application.fullName}</p><a className="mt-1 block underline" href={`mailto:${application.email}`} style={{ color: "var(--color-burgundy)" }}>{application.email}</a></td><td className="px-5 py-4" style={{ color: "var(--color-stone)" }}>{application.courseProgram}</td><td className="px-5 py-4" style={{ color: "var(--color-stone)" }}>{application.yearLevelSection}</td><td className="px-5 py-4" style={{ color: "var(--color-stone)" }}><p>{application.contactNumber || "-"}</p>{application.facebookProfile && <a className="mt-1 block underline" href={application.facebookProfile} rel="noreferrer" target="_blank" style={{ color: "var(--color-burgundy)" }}>Facebook profile</a>}</td><td className="px-5 py-4" style={{ color: "var(--color-stone)" }}>{new Date(application.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div>;
}
